### ISSUE TITLE
require.js sometimes throws Load Timeout even though it never started loading the file

### ISSUE THREAD

**Issue by cowwoc** [jrburke/requirejs#1257]
I've been able to consistently reproduce a problem where require.js loads modules for 200ms, then sits there until `waitSeconds` expires and throws an error complaining that a certain module never loaded in time. Thing is, I can see that require.js never even tries to load the module in question.

Take a look at the log I posted over at https://github.com/guybedford/require-css/issues/177#issuecomment-68548826. Do you think this issue is related to https://github.com/jrburke/requirejs/issues/1046?

I don't have a minimal testcase for reproducing the problem, but I am able to reproduce it locally fairly consistently. It occurs roughly 10% of the time, so if I run 10 unit tests in a row I tend to run into this bug at least once.

The posted log doesn't contain timestamp values but shortly after posting the comment I added them by logging `var timeElapsed = new Date().getTime() - context.startTime` for each line.

@jrburke I am not going to be able to resolve this without your help. How do I go about debugging this further?

**Comment by sequomics** [comment]
Hi,
I am doing some work with requirejs, because i am a fan of it.
Recently, i have started a large project. In this i have to install more than 60 dependencies.

Now, i am facing same issue over here.

So, please help me out.

Thanks.

**Comment by jrburke** [comment]
I suspect that the loader plugin is not calling back to requirejs to indicate it is done or needs a module. To know more though, some sort of test case is needed.

Going to close for now, but please feel free to leave more information and hopefully a link to a test case, and we can reopen as needed.

**Comment by sequomics** [comment]
Thanks for now.

I will hopefully send you a link for test case.

On 24/01/2015, James Burke <notifications@github.com> wrote:
> I suspect that the loader plugin is not calling back to requirejs to
> indicate it is done or needs a module. To know more though, some sort of
> test case is needed.
>
> Going to close for now, but please feel free to leave more information and
> hopefully a link to a test case, and we can reopen as needed.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jrburke/requirejs/issues/1257#issuecomment-71279070


-- 
Prabhat Kumar
[CEO & Founder]
Sequomics Corporation

**Comment by cowwoc** [comment]
@jrburke I don't think I will be able to provide you with a minimal testcase because this problem occurs randomly, and only with bigger projects. I believe that we should be able to track down the problem to the source if you instruct me on where to add logging. Where does the loader plugin "call back to requirejs to indicate it is done or needs a module"?

**Comment by sequomics** [comment]
Hi,
  Yes, this is right. for bigger projects it is coming.
Right now, i am using more than 60 scripts in my project like, jquery,
jquery based plugins, knockout, durandal framework, socket.io, amplify
and many others own written modules to become as a SPA.

When i am calling through AMD, i am facing same problem.

Please have a look in to this.

Thanks.

On 26/01/2015, Gili Tzabari <notifications@github.com> wrote:
> @jrburke I don't think I will be able to provide you with a minimal testcase
> because this problem occurs randomly, and only with bigger projects. I
> believe that we should be able to track down the problem to the source if
> you instruct me on where to add logging. Where does the loader plugin "call
> back to requirejs to indicate it is done or needs a module"?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jrburke/requirejs/issues/1257#issuecomment-71393834


-- 
Prabhat Kumar
[CEO & Founder]
Sequomics Corporation

**Comment by sequomics** [comment]
Hi,
Here is the test case image:
![require js-error](https://cloud.githubusercontent.com/assets/10467897/5904871/d62b5c46-a5b1-11e4-9fff-a7019956fed3.PNG)

Thanks.

**Comment by Paulche** [comment]
I run into the same bug.
FYI: In my case ship caused this bug. I converted module from shim to regular one.
I hope it helps.

**Comment by sequomics** [comment]
Hi,
I did something else to get rid of this bug, try to use require calls through "deps:[...]", and put waitSeconds.

May be your problem will resolved.

Thanks.

**Comment by cowwoc** [comment]
You're not actually changing this bug. You're simply changing the timing which reduces the probability of the problem occurring, but the bug is still there.

**Comment by lucasroselli** [comment]
I'm facing the same issue, and started when the application got bigger
just like @cowwoc said it happens randomly

**Comment by patrickkunka** [comment]
Facing the same issue here only when I run my project in its non-optimized dev mode. My project has about 75 dependencies. Requires will often throw a seemingly random loadTimeout error on startup, and on a different module or modules each time.

Hard to create a test case because the behaviour is never consistent.

**Comment by lucasroselli** [comment]
I finally solved my problem!! I just removed all chrome extensions! It work's for me.

**Comment by patrickkunka** [comment]
Interesting - I'll give that a go!

I'm starting to think my issue is actually server side (perhaps to do with my Express static middleware) as I can see that the files are question are actually being requested in my express logger, although the requests don't show up in the chrome network panel. This may well be nothing todo with require.

**Comment by cowwoc** [comment]
@lucasroselli Obviously changing the timings will shift the problem. This doesn't mean the bug is gone. It just means it moved elsewhere.

The fact that requirejs throws a timeout without even starting to load the file indicates there is still a bug there.

**Comment by patrickkunka** [comment]
I fixed my issue by resolving the issues on the back-end (removing some junk express middleware that I wasn't using if it helps anyone).

Although the modules that timed out were not shown in the chrome network panel, the requests had indeed been made by require, as I could see them on the server logs. @cowwoc When you say require had not even started to load the file, is that what you mean?

**Comment by cowwoc** [comment]
I added a println() at the point where requirejs begins loading the remote
file. I could see it loading some files but not the one that timed out.

Anyway, I have given up on requirejs and am now using webpack which does
not exhibit this problem.

**Comment by lucasroselli** [comment]
@cowwoc sorry but you are wrong, I created a project with just one file on require, even increasing the timeout the error persists, and only on chrome, how can you say that ? But when I removed the chrome extensions it did work, yesterday the error occurred in another machine, only on chrome again, I ask him to disable all chrome extensions and it did work again, if you want I can pass you the project.

Obviously some extensions ( probably the internet backing security extensions ) was blocking the download.

**Comment by jrburke** [comment]
@lucasroselli if you can isolate it to a particular chrome extension, that would help others avoid it, maybe we can contact the extension author to fix that root cause.

**Comment by lucasroselli** [comment]
@jrburke it's a brazilian bank extension, I just meant to report my case for others who might have the same issue, but today's the application has more than 600 js files and it's working perfectly, so it wasn't the amount of file which I reported earlier

**Comment by cowwoc** [comment]
@lucasroselli Maybe your case differs from mine. All I can tell you is that as part of my investigation I added a `print()` statement inside RequireJS immediately before it begins loading the external JS file. I consistently saw RequireJS complaining about a load timeouts for files it never even began to load.

If an extension really was at fault, you'd see the `print()` statement saying that RequireJS is about to load the file, followed by a delay (caused by the extension), followed by a timeout error. In my case, this never took place.

@jrburke as I mentioned in the past, it would help a lot if you could add logging into RequireJS's official release. This would allow users to diagnose such problems without needing to understand library internals.

**Comment by Lumaraf** [comment]
I had the same problem and was able to reproduce it with a small test case.
I posted a Issue for this at https://github.com/jrburke/requirejs/issues/1440

**Comment by chrisknoll** [comment]
I've seen tomeout errir when two fifferent module ids request the same uri.  With larger projects that have relative module ids declared, its more likely you will have this sort of mistake. Could this be the issue?  @cowwoc, does your print debug include the requested module id and url to load? You should check for dupes

**Comment by Gudz0l** [comment]
Hi Guys,
I also faced with this this issue. Please note I am not a developer, but I am Oracle DBA who assist to our development team to install and configure their products.
Root cause of the issue in our case was very slow internet connectivity from servers to our location 20-30 Kb/s. Default window to load module is 7 seconds it's mean that in best case scenario we will be able to receive 210 Kb of data which usually is not enough for proper work as result we see time out error in console. After we fix issue with our network issue is gone.
